### ISSUE TITLE
Tests broken by banning rule inferences adding roles to existing relations

### ISSUE THREAD

**Issue by maxbaxt** [graknlabs/behaviour#109]
All tests that have been disabled are tagged with the following comment:
`#  TODO: disabled because added new roles to existing relations no longer allowed in rule heads`

- [ ]  All these tests need to be edited to coincide with the new restrictions, or deleted.

**Comment by alexjpwalker** [comment]
Resolved by the addition of this scenario in `rule-validation.feature`:

```gherkin
  Scenario: when a rule adds a role to an existing relation, an error is thrown
    Checks adding new roles to existing relationships is not allowed
    When graql define; throws exception
      """
      define

      rule add-bob-to-all-employment:
      when {
        $r isa employment;
        $p isa person, has name bob;
      } then {
        $r (employee: $p) isa employment;
      };
      """
```
