### ISSUE TITLE
Test overriding 'plays', 'owns', etc. when defining types

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/behaviour#141]
We need Graql Define tests for overriding 'plays', 'owns' and so on.

We discovered recently that:
```graql
define
locates relates located;
contractor-locates sub locates, relates contractor-located as located;

employment sub relation, relates employee, plays locates:located;
contractor-employment sub employment, plays contractor-locates:contractor-located as located;
```
causes a NPE to be thrown on the server.

See https://github.com/graknlabs/grakn/issues/6032 - we would have caught this severe bug much sooner, if we had these scenarios.

**Comment by haikalpribadi** [comment]
Fixed by: https://github.com/graknlabs/behaviour/pull/147
